All tasks of module 3 have been solved
js-tasks-ru/jsbasic-20201214_yanshatskiy pull request #4
Opened 2020-12-27 11:57 UTC by jan-web

Sorry, I'm late. The tasks were very interesting.

2020-12-27 12:04 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Фильтрация по диапазону
+ не должна менять исходный массив
+ должна фильтровать диапазон
```
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать '-webkit-transition'
+ должна преобразовать 'list-style-image' 
+ должна оставить пустую строку без изменений 
+ должна преобразовать 'background-color'
```
```diff
Функция showSalary(users, age)
+ для пользователей до 40 лет должна вывести строку с зарплатами
+ для пользователей до 30 лет должна вывести строку с зарплатами
```
```diff
Найти min/max в строке
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
+ 25,-1,-234,4,   1000
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-27 18:49 UTC, SinimaWath requested changes

2020-12-27 18:49 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return users.map((user) => user.name);
Давай деструктрозацию

2020-12-27 18:49 UTC, SinimaWath commented on 3-module/3-task/index.js
> +    .map((word) => (word === "" ? " " : word[0].toUpperCase() + word.slice(1)))
Давай просто: '!word'

2020-12-27 18:49 UTC, SinimaWath commented on 3-module/4-task/index.js
> +    return result;
Не хватает отступа сверху от if

2020-12-27 18:49 UTC, SinimaWath commented on 3-module/5-task/index.js
> +      return numbers;
тут тоже не хватает отступа

2020-12-28 11:07 UTC, jan-web commented on 3-module/4-task/index.js
> +    return result;
Вы имеете в виду между     if(user.age <= age) {
      и
      return result + user.name + ', ' + user.balance + '\n';
      Prettier в VScode  убирает этот отступ как "некрасивый" :)

2020-12-28 11:08 UTC, jan-web commented on 3-module/5-task/index.js
> +      return numbers;
Я поставлю. Проверьте пожалуйста правильно ли я понял.

2020-12-28 11:12 UTC, jan-web commented on 3-module/4-task/index.js
> +    return result;
Между     } и 
    return result;
    нужен отступ?

2020-12-28 11:24 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция showSalary(users, age)
+ для пользователей до 30 лет должна вывести строку с зарплатами
+ для пользователей до 40 лет должна вывести строку с зарплатами
```
```diff
Найти min/max в строке
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
+ 25,-1,-234,4,   1000
```
```diff
Фильтрация по диапазону
+ не должна менять исходный массив
+ должна фильтровать диапазон
```
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать '-webkit-transition'
+ должна оставить пустую строку без изменений 
+ должна преобразовать 'background-color'
+ должна преобразовать 'list-style-image' 
```
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-29 12:59 UTC, SinimaWath commented on 3-module/4-task/index.js
> +    return result;
Да, между } и return result

2020-12-29 13:00 UTC, SinimaWath commented on 3-module/5-task/index.js
> +      return numbers;
Имел ввиду вот так:

```
if (...) {
  numbers.push
}

return
```

2020-12-29 14:03 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Фильтрация по диапазону
+ должна фильтровать диапазон
+ не должна менять исходный массив
```
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Функция showSalary(users, age)
+ для пользователей до 40 лет должна вывести строку с зарплатами
+ для пользователей до 30 лет должна вывести строку с зарплатами
```
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать '-webkit-transition'
+ должна преобразовать 'list-style-image' 
+ должна оставить пустую строку без изменений 
+ должна преобразовать 'background-color'
```
```diff
Найти min/max в строке
+ 25,-1,-234,4,   1000
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-29 14:04 UTC, SinimaWath approved these changes

2020-12-29 14:04 UTC, merged