The tasks of module 4 have been solved
js-tasks-ru/jsbasic-20201214_yanshatskiy pull request #5
Opened 2021-01-04 13:36 UTC by jan-web

It was possible to do better.

2021-01-04 13:46 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция highlight
+ Проставит класс available/unavailable, в зависимости от значения атрибута data-available у ячейки Status
+ Проставит аттрибут hidden, если  data-available атрибута нет вообще
+ Проставит класс male/female, в зависимости от содержимого ячекйки Gender
+ Установит inline-стиль style="text-decoration: line-through", если значение ячейки Age меньше 18
```
```diff
Выделите ячейки по диагонали
+ должна окрашивать ячейку второй строки в красный
+ должна окрашивать ячейку третьей строки в красный
+ должна окрашивать ячейку четвёртой строки в красный
+ должна окрашивать ячейку пятой строки в красный
+ должна окрашивать ячейку первой строки в красный
```
```diff
Функция makeFriendsList(friends)
+ Число элементов в списке и число объектов в массиве должны быть одинаковыми
+ проверяем содержимое списка
+ функция должна возвращать HTML список
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2021-01-04 17:56 UTC, SinimaWath requested changes

2021-01-04 17:56 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  friends.forEach(el => element.insertAdjacentHTML('beforeend', `<li>${el.firstName} ${el.lastName}</li>`));
Все ок, давай только выделим шаблон(<li>${el.firstName} ${el.lastName}</li>) в отдельную функцию

2021-01-04 17:56 UTC, SinimaWath commented on 4-module/2-task/index.js
> +  tRows.map((row, index) => (row.children[index].style.background = "red"));
Круто!

2021-01-04 17:56 UTC, SinimaWath commented on 4-module/2-task/index.js
> +  tRows.map((row, index) => (row.children[index].style.background = "red"));
Только тут можно, использовать не map, a forEach

2021-01-04 17:56 UTC, SinimaWath commented on 4-module/3-task/index.js
> +		}
Этот код не очень читабельный, из-за тернароного оператора.

В таких случаях, лучше использовать обычный if

2021-01-05 06:58 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция highlight
+ Проставит класс available/unavailable, в зависимости от значения атрибута data-available у ячейки Status
+ Проставит аттрибут hidden, если  data-available атрибута нет вообще
+ Проставит класс male/female, в зависимости от содержимого ячекйки Gender
+ Установит inline-стиль style="text-decoration: line-through", если значение ячейки Age меньше 18
```
```diff
Выделите ячейки по диагонали
+ должна окрашивать ячейку пятой строки в красный
+ должна окрашивать ячейку четвёртой строки в красный
+ должна окрашивать ячейку первой строки в красный
+ должна окрашивать ячейку третьей строки в красный
+ должна окрашивать ячейку второй строки в красный
```
```diff
Функция makeFriendsList(friends)
+ функция должна возвращать HTML список
+ Число элементов в списке и число объектов в массиве должны быть одинаковыми
+ проверяем содержимое списка
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2021-01-05 16:55 UTC, SinimaWath commented on 4-module/3-task/index.js
> +	[...table.querySelectorAll("tr")].map((row, index) => {
Тут тоже forEach.

forEach - чтобы обойти и не изменять исхоодный массив
map - чтобы преобразовать массив в другой

2021-01-05 17:45 UTC, jan-web commented on 4-module/3-task/index.js
> +	[...table.querySelectorAll("tr")].map((row, index) => {
Тут только логический довод? Так как не нужен новый массив то и не нужно использовать map.
По сути же то же самое происходит. И map не мутирующий метод и не меняет исходный массив.
Только для лучшего понимания кода другим человеком который захочет в нем разобраться ? Верно?

2021-01-05 17:47 UTC, SinimaWath commented on 4-module/3-task/index.js
> +	[...table.querySelectorAll("tr")].map((row, index) => {
Да логический довод: map - маппит(преобразует) элементы массивы и возвращает новый массив, с этими преобразованными данными.

Но в твоем коде, ты не используешь результирующий массив

2021-01-05 18:55 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция makeFriendsList(friends)
+ проверяем содержимое списка
+ Число элементов в списке и число объектов в массиве должны быть одинаковыми
+ функция должна возвращать HTML список
```
```diff
Выделите ячейки по диагонали
+ должна окрашивать ячейку третьей строки в красный
+ должна окрашивать ячейку пятой строки в красный
+ должна окрашивать ячейку четвёртой строки в красный
+ должна окрашивать ячейку второй строки в красный
+ должна окрашивать ячейку первой строки в красный
```
```diff
Функция highlight
+ Проставит аттрибут hidden, если  data-available атрибута нет вообще
+ Проставит класс male/female, в зависимости от содержимого ячекйки Gender
+ Проставит класс available/unavailable, в зависимости от значения атрибута data-available у ячейки Status
+ Установит inline-стиль style="text-decoration: line-through", если значение ячейки Age меньше 18
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2021-01-07 17:07 UTC, SinimaWath approved these changes

2021-01-07 17:07 UTC, merged